on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches:
      - main
      - master
name: Test Go Tip
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Install Go tip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
          gotip version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - id: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
          key: ubuntu-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ubuntu-go-
      - name: Dependencies
        run: gotip mod download
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Test
        run: gotip test ./...
      - name: Test 32 bit
        env:
          GOARCH: 386
        run: gotip test ./...
      - name: Test with race detector
        run: gotip test -race ./...
